baseURL = "http://seissol.github.io/"
languageCode = "en-us"
title = "SeisSol"
enableRobotsTXT = true

[menu]
    [[menu.main]]
    name = "GitHub"
    url = "https://github.com/SeisSol/SeisSol"
    params = { icon = "fa fa-external-link" }

    [[menu.main]]
    name = "Docs"
    url = "https://seissol.readthedocs.io"
    params = { icon = "fa fa-external-link" }
